# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Goncalves-lab
tagline:          'Goncalves-lab'
description:      'Website of the Somatic Evolution and Early Detection research group at the German Cancer Research Center (DKFZ) in Heidelberg, Germany'
url:              http://goncalves-lab.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
