# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Goncalves lab
tagline:          'Goncalves lab'
description:      'Website of the Somatic Evolution and Early Detection research group at the DKFZ in Heidelberg, Germany'
url:              http://goncalves-lab.github.io/
baseurl:          /

author:
  name:           'Angela Goncalves'
  url:            https://twitter.com/afilimon

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/goncalves-lab
